export const ADD_LIST="ADD_LIST"
export const DELETE_LIST="DELETE_LIST"
export const MOVE_LIST="MOVE_LIST"
export const ADD_TASK="ADD_TASK"
export const DELETE_TASK="DELETE_TASK"
export const MOVE_TASK="MOVE_TASK"
export const SET_DRAGGED_ITEM="SET_DRAGGED_ITEM"